### ISSUE TITLE
Error on line $dyb->connect(true); ?

### ISSUE THREAD

**Issue by chenthomas** [doyoubuzz/api-helper#2]
Hi,

Thanks for the git repo, im using your API Helper and i was wondering why Im getting an error when im calling the connect function. 

I tried to var_dump($dyb);
and it gives me : object(DoYouBuzz\ApiHelper\DoYouBuzzAPI)#1 (6) { ["apiKey":protected]=> string(20) "XXXXXXXXXX" ["apiSecret":protected]=> string(25) "XXXXXXXXXX" ["service":protected]=> NULL ["storage":protected]=> NULL ["currentUri":protected]=> NULL ["init":"DoYouBuzz\ApiHelper\DoYouBuzzAPI":private]=> bool(false) }

Can you help me to fix my issue ? 

Thank you

**Comment by Bacteries** [comment]
Can you give us more informations on the error you get when you trying to connect?

**Comment by chenthomas** [comment]
Hi, I used an other git repo https://github.com/doyoubuzz/dyb-api-connexion-php which is working perfectly for me. I didn't figure it out where was the issue on your api-helper tho... maybe I didn't configure well the autoloader...
Thank you anyway for your reply,
Cheers

**Comment by Bacteries** [comment]
OK. The Api Helper have a dependency (on lusitanian/oauth), so if you don't install it with composer it might be the source of your problem.

Don't hesitate to share your app with us when done ;)
